'use strict';
function escC(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function applyThemeC(theme){const dark=theme==='dark';document.body.dataset.theme=dark?'dark':'light';const t=document.getElementById('theme-toggle');if(t){t.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');t.setAttribute('aria-pressed',dark?'true':'false');}}
function initThemeC(){let v='light';try{v=localStorage.getItem('merit-register-theme')||'light';}catch(e){}applyThemeC(v);const t=document.getElementById('theme-toggle');if(t)t.onclick=()=>{const n=document.body.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('merit-register-theme',n)}catch(e){}applyThemeC(n);};}
const PROFILE_KEY_C='merit-register-candidate-profile-v1',SHORTLIST_KEY_C='shortlist',ORDER_KEY_C='preference_order';
const COLLEGE_BY_ID=Object.fromEntries((typeof ALL_COLLEGES!=='undefined'?ALL_COLLEGES:[]).map(c=>[Number(c.id),c]));
const CATS_C=['General','OBC','EWS','SC','ST'];const CAT_LABEL_C={General:'General / UR',OBC:'OBC-NCL',EWS:'EWS',SC:'SC',ST:'ST'};
const ELIG_C=[['du','DU'],['ip','IPU'],['esi','ESI'],['amu','AMU'],['puducherry','Puducherry'],['cw_du','CW-DU'],['cw_ip','CW-IPU'],['foreign','Foreign'],['amu_nri','AMU NRI']];
function parseC(v,f){try{const x=JSON.parse(v);return x??f}catch(e){return f}}
function getC(k,f=''){try{const v=localStorage.getItem(k);return v===null?f:v}catch(e){return f}}
function profileC(){const v=parseC(getC(PROFILE_KEY_C,'{}'),{}),air=Number(v.air);return {air:Number.isFinite(air)&&air>0?Math.floor(air):null,category:CATS_C.includes(v.category)?v.category:'General',domicile:String(v.domicile||''),eligibilities:(v.eligibilities&&typeof v.eligibilities==='object')?v.eligibilities:{}};}
function saveProfileC(p){try{localStorage.setItem(PROFILE_KEY_C,JSON.stringify(p))}catch(e){}}
function idsC(k){return [...new Set(parseC(getC(k,'[]'),[]).map(Number).filter(id=>Number.isFinite(id)&&typeof COLLEGE_BY_ID!=='undefined'&&(COLLEGE_BY_ID[id]||COLLEGE_BY_ID[String(id)])))]}
function saveIdsC(k,a){try{localStorage.setItem(k,JSON.stringify(a))}catch(e){}}
function rankC(v){const n=Number(v);return Number.isFinite(n)&&n>0?n:null}function fmtC(v){const n=rankC(v);return n?n.toLocaleString('en-IN'):'—'}
function recC(id,year){if(year===2026&&typeof AIQ_CUTOFFS_2026!=='undefined')return AIQ_CUTOFFS_2026[id]||AIQ_CUTOFFS_2026[String(id)]||null;if(year===2025&&typeof CUTOFFS!=='undefined')return CUTOFFS[id]||CUTOFFS[String(id)]||null;return null;}
function roundsC(r,cat){if(!r)return null;if(r.category_rounds&&r.category_rounds[cat])return r.category_rounds[cat];if(cat==='General'&&r.rounds)return r.rounds;if(r.categories_final_round&&r.categories_final_round[cat]!=null)return {Final:Number(r.categories_final_round[cat])};return null;}
function streamMetaC(code){const m=(typeof MCC_QUOTA_STREAMS!=='undefined'&&MCC_QUOTA_STREAMS&&MCC_QUOTA_STREAMS[code])||null;return m||{short_label:code,label:code};}
function eligibleCodesC(p){const out=['AI','SO'],fallback={du:'DU',ip:'IP',esi:'ES',amu:'AM',puducherry:'JP',cw_du:'DW',cw_ip:'IW',foreign:'FQ',amu_nri:'AN'};Object.entries(fallback).forEach(([k,c])=>{if(p.eligibilities?.[k]&&!out.includes(c))out.push(c)});return out;}
function routesC(id,p){if(!p.air||typeof MCC_CUTOFFS_2026_BY_QUOTA==='undefined')return [];const all=MCC_CUTOFFS_2026_BY_QUOTA[id]||MCC_CUTOFFS_2026_BY_QUOTA[String(id)]||{},allowed=new Set(eligibleCodesC(p)),rows=[];Object.entries(all).forEach(([code,r])=>{if(!allowed.has(code))return;const rr=roundsC(r,p.category),cut=rankC(rr&&rr.R1);if(!cut)return;const margin=cut-p.air,meta=streamMetaC(code);rows.push({code,label:meta.short_label||meta.label||code,cutoff:cut,margin,state:margin>=0?'reached':'missed-current',relative:margin/cut});});rows.sort((a,b)=>a.state!==b.state?(a.state==='reached'?-1:1):b.cutoff-a.cutoff);return rows;}
function bestRouteC(id,p){return routesC(id,p)[0]||null}function bandC(r){if(!r)return {label:'Unknown',cls:'unknown'};if(r.relative>=.15)return {label:'Safety',cls:'safety'};if(r.relative>=.03)return {label:'Likely',cls:'likely'};if(r.relative>=-.08)return {label:'Competitive',cls:'competitive'};return {label:'Dream',cls:'dream'};}
function histC(id,p,round){const r=recC(id,2025),rr=roundsC(r,p.category);const cut=rankC(rr&&rr[round]);return {cutoff:cut,record:r};}
function movementC(id,p,currentRoute){if(!currentRoute||!['AI','SO'].includes(currentRoute.code))return {value:null,comparable:false};const a=roundsC(recC(id,2026),p.category),b=roundsC(recC(id,2025),p.category),x=rankC(a&&a.R1),y=rankC(b&&b.R1);if(!x||!y)return {value:null,comparable:false};return {value:x-y,comparable:true};}
let orderC=[];
function loadOrderC(){const shortlist=idsC(SHORTLIST_KEY_C),raw=idsC(ORDER_KEY_C),allowed=new Set(shortlist);const clean=raw.filter(id=>allowed.has(id));shortlist.forEach(id=>{if(!clean.includes(id))clean.push(id)});orderC=clean;try{if(JSON.stringify(raw)!==JSON.stringify(clean))localStorage.setItem(ORDER_KEY_C,JSON.stringify(clean))}catch(e){}}
function renderProfileC(){const p=profileC();document.getElementById('choice-air').value=p.air||'';document.getElementById('choice-category').value=p.category;const extras=ELIG_C.filter(([k])=>p.eligibilities?.[k]).map(([,x])=>x);document.getElementById('choice-routes').innerHTML=['AIQ/Open',...extras].map(x=>`<span class="choice-route-chip">${escC(x)}</span>`).join('');}
function currentStatusC(id,p){const r=bestRouteC(id,p);if(!p.air)return {text:'Set AIR',cls:'unknown',band:{label:'Unknown',cls:'unknown'},r:null};if(!r)return {text:'No eligible 2026 R1 cutoff loaded',cls:'unknown',band:{label:'Unknown',cls:'unknown'},r:null};const b=bandC(r);return {text:`${r.label} · R1 ${r.state==='reached'?'reached':'missed'} · cutoff ${fmtC(r.cutoff)}`,cls:r.state,band:b,r};}
function alertsC(rows,p){const out=[];if(!p.air)out.push(['warn','Set your AIR','Reach annotations are disabled until AIR is saved. Your preference order is still usable.']);if(orderC.length<2)out.push(['info','Build a real choice list','Add at least two colleges to My List or rank them in Decision Mode first.']);const unknown=rows.filter(x=>!x.cur.r).length;if(p.air&&unknown)out.push(['info','Some reach data is unknown',`${unknown} choice${unknown===1?' has':'s have'} no eligible 2026 R1 cutoff in the quota routes currently enabled. Unknown is not treated as ineligible.`]);const safety=rows.some(x=>['Safety','Likely'].includes(x.cur.band.label));if(p.air&&rows.length&&!safety)out.push(['warn','No clear R1 anchor in this list','None of the loaded choices is currently classified Safety/Likely for your enabled 2026 R1 routes. That can be intentional, but make sure your final list extends as far down as you genuinely would join.']);out.push(['info','Preference order stays preference order','The simulator never moves an easier college above a college you prefer more. Reach is an annotation, not a desirability score.']);return out;}
function renderC(){const p=profileC(),round=document.getElementById('choice-round').value;const rows=orderC.map((id,i)=>{const c=(typeof COLLEGE_BY_ID!=='undefined'&&(COLLEGE_BY_ID[id]||COLLEGE_BY_ID[String(id)]))||null;if(!c)return null;const cur=currentStatusC(id,p);return {id,c,i,cur,hist:histC(id,p,round),mv:movementC(id,p,cur.r)}}).filter(Boolean);document.getElementById('choice-total').textContent=rows.length;document.getElementById('choice-reached').textContent=rows.filter(x=>x.cur.r?.state==='reached').length;document.getElementById('choice-unknown').textContent=rows.filter(x=>!x.cur.r).length;document.getElementById('choice-anchor').textContent=rows.filter(x=>['Safety','Likely'].includes(x.cur.band.label)).length;const alerts=alertsC(rows,p);document.getElementById('choice-alerts').innerHTML=alerts.length?`<details class="pref-insights-details"><summary>Review ${alerts.length} list check${alerts.length===1?'':'s'}</summary><div class="pref-insights-inner">${alerts.map(a=>`<div class="choice-alert ${a[0]}"><strong>${escC(a[1])}</strong>${escC(a[2])}</div>`).join('')}</div></details>`:'';const list=document.getElementById('choice-list');const empty=document.getElementById('choice-empty');empty.hidden=rows.length>0;list.hidden=!rows.length;if(!rows.length){list.innerHTML='';return;}list.innerHTML=rows.map((x,i)=>{const h=x.hist.cutoff;const mv=x.mv;return `<article class="choice-row"><div class="choice-pos">${i+1}</div><div class="choice-college"><strong><a href="college.html?id=${x.id}">${escC(x.c.name)}</a></strong><small>${escC(x.c.city)} · ${escC(x.c.state)}</small><span class="choice-badge ${escC(x.cur.band.cls)}">${escC(x.cur.band.label)}</span></div><div class="choice-current"><span class="choice-cell-label">2026 current</span><span class="choice-cutoff">${escC(x.cur.text)}${mv?.comparable?`<small>AIQ/Open R1 vs 2025: ${mv.value>0?'+':''}${Math.abs(mv.value).toLocaleString('en-IN')} ranks ${mv.value>0?'softer':'stronger'}</small>`:(x.cur.r&&!['AI','SO'].includes(x.cur.r.code)?'<small>Historical movement for this quota route is not loaded.</small>':'')}</span></div><div class="choice-history"><span class="choice-cell-label">2025 ${escC(round)} reference</span><span class="choice-cutoff">${h?`Cutoff ${fmtC(h)}<small>${p.air?(p.air<=h?'Your AIR was within this historical range':'Your AIR was outside this historical range'):''}</small>`:'—<small>No category-specific reference loaded</small>'}</span></div><div class="choice-move"><button type="button" data-up="${i}" ${i===0?'disabled':''} aria-label="Move up">↑</button><button type="button" data-down="${i}" ${i===rows.length-1?'disabled':''} aria-label="Move down">↓</button></div></article>`}).join('');list.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>moveC(Number(b.dataset.up),-1));list.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>moveC(Number(b.dataset.down),1));}
function moveC(i,d){const j=i+d;if(j<0||j>=orderC.length)return;[orderC[i],orderC[j]]=[orderC[j],orderC[i]];saveIdsC(ORDER_KEY_C,orderC);renderC();}
function saveCandidateC(){const p=profileC();const air=rankC(document.getElementById('choice-air').value),cat=document.getElementById('choice-category').value;p.air=air;p.category=CATS_C.includes(cat)?cat:'General';saveProfileC(p);renderProfileC();renderC();}
function exportTextC(){const p=profileC();return [`The Merit Register — Choice List`,`AIR: ${p.air?fmtC(p.air):'not set'} · ${CAT_LABEL_C[p.category]}`,``,`Preference order:`].concat(orderC.map((id,i)=>{const c=COLLEGE_BY_ID[id]||COLLEGE_BY_ID[String(id)];return `${i+1}. ${c?.name||id}`})).join('\n');}
async function copyC(){const text=exportTextC();try{await navigator.clipboard.writeText(text);const b=document.getElementById('choice-copy');const old=b.textContent;b.textContent='Copied ✓';setTimeout(()=>b.textContent=old,1300)}catch(e){prompt('Copy your choice list:',text)}}
function downloadC(){const blob=new Blob([exportTextC()],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='merit-register-choice-list.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),300);}
function initC(){initThemeC();loadOrderC();renderProfileC();document.getElementById('choice-save-profile').onclick=saveCandidateC;document.getElementById('choice-round').onchange=renderC;document.getElementById('choice-copy').onclick=copyC;document.getElementById('choice-download').onclick=downloadC;window.addEventListener('storage',e=>{if([ORDER_KEY_C,SHORTLIST_KEY_C,PROFILE_KEY_C].includes(e.key)){loadOrderC();renderProfileC();renderC();}});renderC();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initC);else initC();
