'use strict';

const $d=(s,r=document)=>r.querySelector(s);
const escD=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const COLLEGE_BY_ID_D=Object.fromEntries(ALL_COLLEGES.map(c=>[Number(c.id),c]));
const SHORTLIST_KEY_D='shortlist', ORDER_KEY_D='preference_order', WEIGHTS_KEY_D='merit-register-decision-weights-v1', SET_KEY_D='merit-register-decision-set-v1';
const DIMENSIONS_D=[
  {key:'clinical',label:'Clinical exposure',hint:'patient load · specialties'},
  {key:'academics',label:'Academics',hint:'teaching · library'},
  {key:'research',label:'Research',hint:'UG access · projects'},
  {key:'hostel',label:'Hostel',hint:'privacy · comfort · freedom'},
  {key:'campus',label:'Campus / student life',hint:'sports · clubs · social'},
  {key:'networking',label:'City / networking',hint:'external opportunity'}
];
const DEFAULT_WEIGHTS={clinical:5,academics:4,research:3,hostel:3,campus:3,networking:3};
const PRESETS={
  balanced:{clinical:4,academics:4,research:3,hostel:3,campus:3,networking:3},
  clinical:{clinical:5,academics:4,research:2,hostel:2,campus:1,networking:2},
  research:{clinical:4,academics:4,research:5,hostel:2,campus:2,networking:5},
  life:{clinical:3,academics:3,research:2,hostel:5,campus:5,networking:4}
};
const CALIBRATION_D={
64:{clinical:100,academics:100,research:100,campus:82,networking:100},262:{clinical:88,academics:91,research:88,campus:97,networking:76},72:{clinical:98,academics:93,research:87,campus:80,networking:97},69:{clinical:99,academics:96,research:91,campus:84,networking:98},65:{clinical:95,academics:89,research:84,campus:76,networking:97},71:{clinical:94,academics:94,research:88,campus:85,networking:95},49:{clinical:95,academics:86,research:72,campus:60,networking:75},45:{clinical:88,academics:86,research:80,campus:78,networking:72},402:{clinical:99,academics:96,research:94,campus:86,networking:84},220:{clinical:98,academics:91,research:83,campus:85,networking:96},168:{clinical:90,academics:92,research:89,campus:92,networking:79},239:{clinical:92,academics:91,research:91,campus:91,networking:76},372:{clinical:90,academics:91,research:88,campus:96,networking:72},189:{clinical:85,academics:88,research:84,campus:93,networking:76},38:{clinical:89,academics:89,research:85,campus:83,networking:72},255:{clinical:97,academics:98,research:97,campus:92,networking:85},288:{clinical:97,academics:93,research:84,campus:80,networking:82},75:{clinical:96,academics:91,research:82,campus:78,networking:86},360:{clinical:95,academics:90,research:82,campus:77,networking:85},440:{clinical:97,academics:93,research:90,campus:76,networking:92},226:{clinical:99,academics:94,research:89,campus:83,networking:97},230:{clinical:96,academics:91,research:82,campus:78,networking:96},51:{clinical:94,academics:94,research:88,campus:92,networking:88},66:{clinical:88,academics:85,research:70,campus:79,networking:93},129:{clinical:91,academics:87,research:76,campus:82,networking:74},181:{clinical:92,academics:88,research:78,campus:80,networking:80},211:{clinical:94,academics:89,research:79,campus:76,networking:82},248:{clinical:96,academics:91,research:82,campus:78,networking:78},327:{clinical:95,academics:91,research:80,campus:80,networking:92},323:{clinical:98,academics:94,research:87,campus:81,networking:93}
};

function applyThemeD(theme){const dark=theme==='dark';document.body.dataset.theme=dark?'dark':'light';const b=$d('#theme-toggle');if(b){b.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');b.setAttribute('aria-pressed',dark?'true':'false');}}
function initThemeD(){let t='light';try{t=localStorage.getItem('merit-register-theme')||'light';}catch(e){}applyThemeD(t);const b=$d('#theme-toggle');if(b)b.addEventListener('click',()=>{const n=document.body.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('merit-register-theme',n);}catch(e){}applyThemeD(n);});}
function safeParseD(raw,fallback){try{return JSON.parse(raw)||fallback;}catch(e){return fallback;}}
function readIdsD(key){try{return [...new Set((safeParseD(localStorage.getItem(key)||'[]',[])||[]).map(Number).filter(id=>COLLEGE_BY_ID_D[id]))];}catch(e){return [];}}
function writeIdsD(key,ids){try{localStorage.setItem(key,JSON.stringify(ids));}catch(e){}}
function readWeightsD(){try{return {...DEFAULT_WEIGHTS,...safeParseD(localStorage.getItem(WEIGHTS_KEY_D)||'{}',{})};}catch(e){return {...DEFAULT_WEIGHTS};}}
function writeWeightsD(w){try{localStorage.setItem(WEIGHTS_KEY_D,JSON.stringify(w));}catch(e){}}
function candidateD(){try{const p=safeParseD(localStorage.getItem('merit-register-candidate-profile-v1')||'{}',{});return {air:Number(p.air)||null,category:['General','OBC','EWS','SC','ST'].includes(p.category)?p.category:'General',eligibilities:p.eligibilities||{}};}catch(e){return {air:null,category:'General',eligibilities:{}};}}
function fmtRankD(n){return Number.isFinite(Number(n))?Number(n).toLocaleString('en-IN'):'—';}
function recordRoundsD(record,cat){if(!record)return null;if(record.category_rounds?.[cat])return record.category_rounds[cat];if(cat==='General'&&record.rounds)return record.rounds;if(record.categories_final_round?.[cat]!=null)return {Final:Number(record.categories_final_round[cat])};return null;}
function allowedQuotaD(p){const codes=['AI','SO'];const map={du:'DU',ip:'IP',esi:'ES',amu:'AM',puducherry:'JP',cw_du:'DW',cw_ip:'IW',foreign:'FQ',amu_nri:'AN'};Object.entries(map).forEach(([k,v])=>{if(p.eligibilities?.[k])codes.push(v);});return new Set(codes);}
function reachD(id){const p=candidateD();if(!p.air)return {state:'none',label:'AIR not set'};const recs=(typeof MCC_CUTOFFS_2026_BY_QUOTA!=='undefined'&&(MCC_CUTOFFS_2026_BY_QUOTA[id]||MCC_CUTOFFS_2026_BY_QUOTA[String(id)]))||{};const allowed=allowedQuotaD(p);let routes=[];Object.entries(recs).forEach(([code,r])=>{if(!allowed.has(code))return;const rounds=recordRoundsD(r,p.category),cut=Number(rounds?.R1);if(!Number.isFinite(cut)||cut<=0)return;const margin=cut-p.air;routes.push({code,cut,margin,ratio:margin/cut});});routes.sort((a,b)=>(b.margin>=0)-(a.margin>=0)||b.cut-a.cut);if(!routes.length)return {state:'unknown',label:'No eligible 2026 R1 route'};const x=routes[0];if(x.margin>=0){const band=x.ratio>=.15?'Safety':x.ratio>=.03?'Likely':'Competitive';return {state:'reached',label:`${band} · R1 reached`,cut:x.cut,margin:x.margin};}if(x.ratio>=-.08)return {state:'competitive',label:'Competitive · narrow R1 miss',cut:x.cut,margin:-x.margin};return {state:'dream',label:'Dream · R1 currently stronger',cut:x.cut,margin:-x.margin};}

function textOrdinalD(v){const t=String(v||'').toLowerCase();if(!t)return null;if(/excellent|exceptional|very strong|outstanding|huge|massive|extensive|broad tertiary|major regional|24.?7|high-volume|high volume/.test(t))return 4;if(/strong|good|large|active|modern|spacious|broad|well[- ]?equipped/.test(t))return 3.3;if(/mixed|moderate|medium|adequate|varies|compact|functional/.test(t))return 2.3;if(/weak|poor|limited|deteriorated|overcrowd|dilapidated|problem|not verified|not reconstructed/.test(t))return 1.3;return 2.5;}
function parseLargestNumberD(text){const t=String(text||'').replace(/,/g,'');const vals=[...t.matchAll(/\b(\d+(?:\.\d+)?)\s*(million|m|lakh|k|thousand)?\b/gi)].map(m=>{let v=Number(m[1]);const u=(m[2]||'').toLowerCase();if(u==='million'||u==='m')v*=1e6;else if(u==='lakh')v*=1e5;else if(u==='k'||u==='thousand')v*=1e3;return v;}).filter(Number.isFinite);return vals.length?Math.max(...vals):null;}
function clinicalRawD(d){if(!d)return null;let s=0,k=0;const add=(v,w=1)=>{if(Number.isFinite(v)){s+=v*w;k+=w;}};const beds=parseLargestNumberD(d.beds);if(beds)add(Math.min(4,1+Math.log10(Math.max(beds,100)/100)*1.55),1.1);const opd=parseLargestNumberD(d.opd);if(opd)add(Math.min(4,1+Math.log10(Math.max(opd,1000)/1000)*.95),1.35);add(textOrdinalD(d.superspecialty),1);add(textOrdinalD(d.trauma),.6);return k?s/k:null;}
function averageD(vals){const x=vals.filter(Number.isFinite);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null;}
function researchRawD(d){return d?averageD([textOrdinalD(d.researchStrength),textOrdinalD(d.undergradAccess),textOrdinalD(d.funding),textOrdinalD(d.infrastructure),textOrdinalD(d.studentOpportunities)]):null;}
function academicRawD(d){return d?averageD([textOrdinalD(d.teachingModel),textOrdinalD(d.clinicalTeaching),textOrdinalD(d.library),textOrdinalD(d.learningEnvironment)]):null;}
function campusRawD(d){return d?averageD([textOrdinalD(d.sports),textOrdinalD(d.clubs),textOrdinalD(d.fest),textOrdinalD(d.social)]):null;}
function networkingRawD(d){return d?textOrdinalD(d.cityNetworking||d.city):null;}
function pctRawD(raw){return Number.isFinite(raw)?Math.max(0,Math.min(100,((raw-1)/3)*100)):null;}
function hBoolD(v,yes=3.4,no=1.6){return v===true?yes:v===false?no:null;}
function hostelTextD(h,...keys){return keys.map(k=>k.split('.').reduce((o,x)=>o?.[x],h)).filter(Boolean).join(' ').toLowerCase();}
function hostelScoreD(h){if(!h)return null;let groups=[];let vals=[];const room=hostelTextD(h,'roomAllocation.year1','roomAllocation.year2','roomAllocation.year3','roomAllocation.year4','genderRoomAllocation.boys','genderRoomAllocation.girls','bathroom');if(/single/.test(room))vals.push(4);if(/double|two-seater|two seater/.test(room))vals.push(2.8);if(/triple|dorm/.test(room))vals.push(1.7);if(/attached/.test(room)&&!/common/.test(String(h.bathroom||'').toLowerCase()))vals.push(4);else if(/common/.test(String(h.bathroom||'').toLowerCase()))vals.push(2.2);if(vals.length)groups.push(averageD(vals));vals=[];[h.hygiene,h.roomCondition,h.housekeeping].forEach(x=>{if(x)vals.push(textOrdinalD(x));});if(vals.length)groups.push(averageD(vals));vals=[];[h.wifi,h.powerBackup,h.hotWater,h.drinkingWater,h.acAllowed,h.coolerAllowed].forEach(x=>{const v=hBoolD(x);if(v!=null)vals.push(v);});if(vals.length)groups.push(averageD(vals));const cur=String(h.curfew||'').toLowerCase();if(cur)groups.push(/no fixed|no curfew|flexible|loose/.test(cur)?4:/strict|10\s*pm|11\s*pm/.test(cur)?1.8:2.5);return groups.length?pctRawD(averageD(groups)):null;}
function dimensionScoreD(c,key){const row=CALIBRATION_D[c.id];if(row&&Number.isFinite(row[key]))return row[key];if(key==='clinical')return pctRawD(clinicalRawD(CLINICAL_EXPOSURE[c.id]));if(key==='academics')return pctRawD(academicRawD(ACADEMICS_TEACHING[c.id]));if(key==='research')return pctRawD(researchRawD(RESEARCH_USMLE[c.id]));if(key==='campus')return pctRawD(campusRawD(CAMPUS_STUDENT_LIFE[c.id]));if(key==='networking')return pctRawD(networkingRawD(RESEARCH_USMLE[c.id]));if(key==='hostel')return hostelScoreD(HOSTELS[c.id]);return null;}
function cultureD(id){return (typeof JUNIOR_CULTURE!=='undefined'&&(JUNIOR_CULTURE[id]||JUNIOR_CULTURE[String(id)]))||null;}
function cultureToneD(jc){return String(jc?.signal?.tone||'insufficient').toLowerCase();}
function cultureLabelD(jc){if(!jc)return 'No profile';return jc.signal?.label||'Culture profile researched';}
function culturePassD(jc,mode){if(mode==='show')return true;if(mode==='profile')return !!jc;if(mode==='not-insufficient')return !!jc&&cultureToneD(jc)!=='insufficient';if(mode==='no-concern')return !!jc&&!['concern','watch'].includes(cultureToneD(jc));return true;}
function fitD(c,w){let num=0,den=0,known=0,selected=0;const dims={};DIMENSIONS_D.forEach(d=>{const wt=Number(w[d.key])||0;if(wt<=0)return;selected++;const score=dimensionScoreD(c,d.key);dims[d.key]=score;if(Number.isFinite(score)){known++;num+=score*wt;den+=wt;}});return {score:den?num/den:null,known,selected,coverage:selected?known/selected:0,dims};}
function financeSnippetD(id){const f=FEES_BOND_STIPEND[id];if(!f)return 'Finance layer not reconstructed.';const fee=f.academicFee&&String(f.academicFee).slice(0,135);const bond=f.bond&&String(f.bond).slice(0,145);return [fee&&`Fee: ${fee}`,bond&&`Bond: ${bond}`].filter(Boolean).join(' · ')||'Finance details remain incomplete.';}
function cultureSnippetD(id){const jc=cultureD(id);if(!jc)return 'Junior Culture profile not researched.';return jc.currentPicture||jc.signal?.label||'Culture evidence available.';}
function shortD(s,n=170){s=String(s||'').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1)+'…':s;}

let weightsD=readWeightsD();
let selectedD=[];
function loadSetD(){const saved=readIdsD(SET_KEY_D);const shortlist=readIdsD(SHORTLIST_KEY_D);selectedD=saved.length?saved:shortlist;}
function saveSetD(){writeIdsD(SET_KEY_D,selectedD);}
function renderWeightsD(){const box=$d('#weight-controls');box.innerHTML=DIMENSIONS_D.map(d=>`<div class="weight-row"><label for="weight-${d.key}">${escD(d.label)}<small>${escD(d.hint)}</small></label><input id="weight-${d.key}" data-key="${d.key}" type="range" min="0" max="5" step="1" value="${Number(weightsD[d.key])||0}"/><span class="weight-value" id="weight-value-${d.key}">${Number(weightsD[d.key])||0}</span></div>`).join('');box.querySelectorAll('input').forEach(inp=>inp.addEventListener('input',()=>{weightsD[inp.dataset.key]=Number(inp.value);$d(`#weight-value-${inp.dataset.key}`).textContent=inp.value;writeWeightsD(weightsD);renderD();}));}
function renderCandidateD(){const p=candidateD(),el=$d('#decision-candidate');if(!p.air){el.innerHTML='<strong>AIR not set</strong><span>Reach badges are hidden. Set your AIR in the Directory or Choice Assistant; fit ranking still works independently.</span>';return;}el.innerHTML=`<strong>AIR ${fmtRankD(p.air)} · ${escD(p.category==='General'?'General / UR':p.category)}</strong><span>2026 R1 reach is shown beside results but never added to the fit score.</span>`;}
function renderChipsD(){const box=$d('#decision-chips');box.innerHTML=selectedD.map(id=>{const c=COLLEGE_BY_ID_D[id];return `<span class="decision-chip">${escD((c?.name||'').replace(/^All India Institute of Medical Sciences/i,'AIIMS'))}<button type="button" data-remove="${id}" aria-label="Remove ${escD(c?.name||'college')}">×</button></span>`;}).join('');box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selectedD=selectedD.filter(id=>id!==Number(b.dataset.remove));saveSetD();renderD();});}
function reachVisibleD(r,mode){if(mode==='all')return true;if(mode==='r1')return r.state==='reached';if(mode==='competitive')return ['reached','competitive'].includes(r.state);return true;}
function renderSummaryD(rows){const scored=rows.filter(x=>Number.isFinite(x.fit.score));const avg=scored.length?averageD(scored.map(x=>x.fit.coverage))*100:0;const culture=scored.filter(x=>x.jc).length;const r1=scored.filter(x=>x.reach.state==='reached').length;$d('#decision-summary').innerHTML=`<div><strong>${scored.length}</strong><span>scored colleges</span></div><div><strong>${Math.round(avg)}%</strong><span>average dimension coverage</span></div><div><strong>${culture}</strong><span>with Junior Culture profile</span></div><div><strong>${r1}</strong><span>currently reached in 2026 R1</span></div>`;}
function badgeD(r){if(r.state==='none'||r.state==='unknown')return `<span class="decision-badge">${escD(r.label)}</span>`;return `<span class="decision-badge ${escD(r.state)}">${escD(r.label)}</span>`;}
function cardD(row,i){const {c,fit,reach,jc}=row;const tone=cultureToneD(jc);const dims=DIMENSIONS_D.map(d=>{const wt=Number(weightsD[d.key])||0,score=fit.dims[d.key];return `<div class="dimension-cell ${wt<=0?'ignored':''}"><span>${escD(d.label)} <strong>${wt<=0?'ignored':Number.isFinite(score)?Math.round(score):'—'}</strong></span><div class="dimension-bar"><i style="width:${wt>0&&Number.isFinite(score)?Math.round(score):0}%"></i></div></div>`;}).join('');const score=Number.isFinite(fit.score)?Math.round(fit.score):null;return `<article class="decision-card"><div class="decision-rank">${i+1}</div><div class="decision-card-main"><h3><a href="college.html?id=${c.id}">${escD(c.name)}</a></h3><div class="decision-loc">${escD(c.city)} · ${escD(c.state)} · ${escD(c.type)}</div><div class="fit-line"><div class="fit-score">${score??'—'}${score!=null?'<span>/100</span>':''}</div><div class="fit-coverage">${fit.known}/${fit.selected} weighted dimensions known · ${Math.round(fit.coverage*100)}% coverage</div></div><div class="fit-note">Fit is recalculated from your current weights. Missing dimensions are omitted, never treated as zero.</div><div class="decision-badges">${badgeD(reach)}<span class="decision-badge ${escD(tone)}">Culture: ${escD(cultureLabelD(jc))}</span></div></div><details class="decision-detail-toggle"><summary>Why this ranking?</summary><div class="decision-card-detail"><div class="dimension-grid">${dims}</div><div class="decision-checks"><div class="decision-check"><strong>Junior Culture check</strong>${escD(shortD(cultureSnippetD(c.id),190))}</div><div class="decision-check"><strong>Fees / bond check</strong>${escD(shortD(financeSnippetD(c.id),190))}</div></div><div class="decision-links"><a href="compare.html?c=${c.id}">Compare →</a><a href="college.html?id=${c.id}">Full evidence profile →</a></div></div></details></article>`;}
function currentRowsD(){const min=Number($d('#coverage-filter')?.value||3),cultureMode=$d('#culture-filter')?.value||'show',reachMode=$d('#reach-filter')?.value||'all';return selectedD.map(id=>{const c=COLLEGE_BY_ID_D[id],fit=fitD(c,weightsD),reach=reachD(id),jc=cultureD(id);return {c,fit,reach,jc};}).filter(x=>x.fit.known>=min&&culturePassD(x.jc,cultureMode)&&reachVisibleD(x.reach,reachMode)).sort((a,b)=>(Number.isFinite(b.fit.score)?b.fit.score:-1)-(Number.isFinite(a.fit.score)?a.fit.score:-1)||b.fit.coverage-a.fit.coverage||a.c.name.localeCompare(b.c.name));}
function renderD(){renderChipsD();const rows=currentRowsD();$d('#decision-count').textContent=rows.length;renderSummaryD(rows);$d('#decision-results').innerHTML=rows.map(cardD).join('');$d('#decision-empty').hidden=selectedD.length>=2;$d('#decision-results').hidden=selectedD.length<2;$d('#decision-summary').hidden=selectedD.length<2;$d('#apply-order').disabled=rows.length<2;}
function searchD(q){q=String(q||'').trim();if(q.length<2)return [];return ALL_COLLEGES.filter(c=>!selectedD.includes(Number(c.id))).filter(c=>typeof collegeSearchMatches==='function'?collegeSearchMatches(c,q):`${c.name} ${c.city} ${c.state}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>(typeof collegeSearchScore==='function'?collegeSearchScore(b,q)-collegeSearchScore(a,q):0)||a.name.localeCompare(b.name)).slice(0,10);}
function initSearchD(){const inp=$d('#decision-search'),box=$d('#decision-search-results');const update=()=>{const rows=searchD(inp.value);box.hidden=!rows.length;box.innerHTML=rows.map(c=>`<button class="search-result" type="button" data-add="${c.id}"><strong>${escD(c.name)}</strong><span>${escD(c.city)} · ${escD(c.state)}</span></button>`).join('');box.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{selectedD.push(Number(b.dataset.add));saveSetD();inp.value='';box.hidden=true;renderD();});};inp.addEventListener('input',update);document.addEventListener('click',e=>{if(!e.target.closest('.college-search-wrap'))box.hidden=true;});}
function applyOrderD(){const rows=currentRowsD();if(rows.length<2)return;const ranked=rows.map(x=>x.c.id);const existing=readIdsD(ORDER_KEY_D),short=readIdsD(SHORTLIST_KEY_D);const all=[...new Set([...short,...selectedD])];const rankedSet=new Set(ranked);const rest=existing.filter(id=>all.includes(id)&&!rankedSet.has(id));all.forEach(id=>{if(!rankedSet.has(id)&&!rest.includes(id))rest.push(id);});if(!confirm(`Apply the current Decision Mode ranking to the top ${ranked.length} colleges in My List? Your other shortlisted colleges will stay below them.`))return;writeIdsD(SHORTLIST_KEY_D,all);writeIdsD(ORDER_KEY_D,[...ranked,...rest]);const b=$d('#apply-order');const old=b.textContent;b.textContent='Applied to My List ✓';setTimeout(()=>b.textContent=old,1800);}
function initD(){initThemeD();loadSetD();renderCandidateD();renderWeightsD();initSearchD();['coverage-filter','culture-filter','reach-filter'].forEach(id=>$d('#'+id)?.addEventListener('change',renderD));$d('#reset-weights').onclick=()=>{weightsD={...DEFAULT_WEIGHTS};writeWeightsD(weightsD);renderWeightsD();renderD();};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{weightsD={...PRESETS[b.dataset.preset]};writeWeightsD(weightsD);renderWeightsD();renderD();});$d('#apply-order').onclick=applyOrderD;renderD();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initD);else initD();
