'use strict';

const TL_PHASES=(typeof FRESHERS_TIMELINE_META!=='undefined'&&Array.isArray(FRESHERS_TIMELINE_META.phases))?FRESHERS_TIMELINE_META.phases:[];
const TL_PUBLISHABLE=new Set(['A','B','C']);
function tlEsc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function tlCollege(id){return (typeof ALL_COLLEGES!=='undefined'?ALL_COLLEGES:[]).find(c=>Number(c.id)===Number(id))||null;}
function tlCulture(id){return (typeof JUNIOR_CULTURE!=='undefined'&&(JUNIOR_CULTURE[String(id)]||JUNIOR_CULTURE[Number(id)]))||null;}
function tlFirst90(id){return (typeof JUNIOR_FIRST90!=='undefined'&&(JUNIOR_FIRST90[String(id)]||JUNIOR_FIRST90[Number(id)]))||null;}
function tlPhases(id){const b=(typeof FRESHERS_TIMELINE!=='undefined'&&(FRESHERS_TIMELINE[String(id)]||FRESHERS_TIMELINE[Number(id)]))||{phases:{}};return TL_PHASES.map(p=>({...p,...(b.phases?.[p.key]||{grade:'GAP',basis:'none',status:'unknown',summary:'No phase-specific evidence reconstructed for this period.',sources:[]})}));}
function tlFormatName(name){return String(name||'').replace(/^All India Institute of Medical Sciences/i,'AIIMS');}
function tlSourceYearMap(id){const m=new Map();const add=s=>{const u=String(s?.url||'').trim();if(u&&Number(s?.year))m.set(u,Number(s.year));};(tlCulture(id)?.sources||[]).forEach(add);(tlFirst90(id)?.sources||[]).forEach(add);return m;}
function tlPhaseYears(id,phase){const map=tlSourceYearMap(id);const years=[];(phase.sources||[]).forEach(s=>{const y=Number(s?.year)||map.get(String(s?.url||'').trim());if(y)years.push(y);});return years;}
function tlSourceClasses(id){const src=[...(tlCulture(id)?.sources||[]),...(tlFirst90(id)?.sources||[])];const kinds=new Set(src.map(s=>s?.kind).filter(k=>['official','news','student'].includes(k)));return {classes:kinds.size,total:new Set(src.map(s=>String(s?.url||s?.label||'').trim()).filter(Boolean)).size,student:kinds.has('student'),official:kinds.has('official'),news:kinds.has('news')};}
function tlFirst90Count(id){const c=tlFirst90(id)?.coverage||{};return ['firstWeeks','residenceMode','genderSpecific','optOut','afterFreshers'].filter(k=>c[k]===true).length;}
function tlEvidenceBreadth(id){const s=tlSourceClasses(id),f=tlFirst90Count(id),p=tlPhases(id).filter(x=>TL_PUBLISHABLE.has(x.grade)).length;return Math.min(100,s.classes*18+Math.min(4,s.total)*5+f*5+p*4);}
function tlMetrics(id){const college=tlCollege(id),jc=tlCulture(id);if(!college||!jc)return null;const phases=tlPhases(id),supported=phases.filter(p=>TL_PUBLISHABLE.has(p.grade)),lead=phases.filter(p=>p.grade==='D');let current=0,historical=0,unknownYear=0;supported.forEach(p=>{const ys=tlPhaseYears(id,p);if(ys.some(y=>y>=2026))current++;else if(ys.length&&ys.every(y=>y<2026))historical++;else unknownYear++;});const breadth=tlEvidenceBreadth(id),first90=tlFirst90Count(id),source=tlSourceClasses(id);const zero=supported.length===0,thin=supported.length===1,dense=supported.length>=3,historicalOnly=supported.length>0&&current===0&&historical>0&&unknownYear===0;let priority=(6-supported.length)*2;if(zero)priority+=4;if(breadth>=55&&zero)priority+=5;if(source.classes>=2&&zero)priority+=2;if(first90>=2&&zero)priority+=1;if(current===0)priority+=1;return {id:Number(id),college,jc,phases,supported:supported.length,lead:lead.length,current,historical,unknownYear,historicalOnly,zero,thin,dense,breadth,first90,source,priority};}
const TL_ROWS=Object.keys(typeof JUNIOR_CULTURE!=='undefined'?JUNIOR_CULTURE:{}).map(tlMetrics).filter(Boolean);

function tlGet(k,f=null){try{const v=localStorage.getItem(k);return v===null?f:v}catch(e){return f}}
function tlSet(k,v){try{localStorage.setItem(k,v);return true}catch(e){return false}}
function tlSetTheme(){const saved=tlGet('merit-register-theme','light');if(saved==='dark')document.body.dataset.theme='dark';const btn=document.getElementById('theme-toggle');if(!btn)return;btn.setAttribute('aria-pressed',document.body.dataset.theme==='dark'?'true':'false');btn.addEventListener('click',()=>{const d=document.body.dataset.theme!=='dark';document.body.dataset.theme=d?'dark':'';tlSet('merit-register-theme',d?'dark':'light');btn.setAttribute('aria-pressed',d?'true':'false');});}
function tlPopulate(){const st=document.getElementById('timeline-state');[...new Set(TL_ROWS.map(r=>r.college.state))].sort().forEach(s=>st.insertAdjacentHTML('beforeend',`<option value="${tlEsc(s)}">${tlEsc(s)}</option>`));const ph=document.getElementById('timeline-phase');TL_PHASES.forEach(p=>ph.insertAdjacentHTML('beforeend',`<option value="${tlEsc(p.key)}">${tlEsc(p.label)}</option>`));const qs=new URLSearchParams(location.search);if(qs.get('phase')&&TL_PHASES.some(p=>p.key===qs.get('phase')))ph.value=qs.get('phase');if(qs.get('status'))document.getElementById('timeline-status').value=qs.get('status');if(qs.get('college')){const raw=qs.get('college');const c=tlCollege(raw);document.getElementById('timeline-search').value=c?c.name:raw;}}
function tlStats(){const supportedCells=TL_ROWS.reduce((n,r)=>n+r.supported,0),leadCells=TL_ROWS.reduce((n,r)=>n+r.lead,0),withTiming=TL_ROWS.filter(r=>r.supported>0).length,current=TL_ROWS.filter(r=>r.current>0).length;const zero=TL_ROWS.length-withTiming;document.getElementById('timeline-stats').innerHTML=[[TL_ROWS.length,'researched profiles'],[withTiming,'with ≥1 A–C phase'],[supportedCells,'A–C supported cells'],[current,'with 2026 phase evidence'],[zero,'with zero supported phases']].map(([n,l])=>`<div class="timeline-stat"><div class="n">${n}</div><div class="l">${l}</div></div>`).join('');return {supportedCells,leadCells,withTiming,current,zero};}
function tlPhaseSummary(){const root=document.getElementById('phase-summary-grid');root.innerHTML=TL_PHASES.map(p=>{const supported=TL_ROWS.filter(r=>TL_PUBLISHABLE.has(r.phases.find(x=>x.key===p.key)?.grade)).length;const lead=TL_ROWS.filter(r=>r.phases.find(x=>x.key===p.key)?.grade==='D').length;return `<button class="phase-card" data-phase="${tlEsc(p.key)}" type="button"><div class="phase-short">${tlEsc(p.short||p.label)}</div><div class="phase-n">${supported}/200</div><div class="phase-d">${200-supported-lead} gaps${lead?` · ${lead} lead`:''}</div></button>`;}).join('');root.querySelectorAll('.phase-card').forEach(b=>b.addEventListener('click',()=>{document.getElementById('timeline-phase').value=b.dataset.phase;document.getElementById('timeline-status').value='missing';root.querySelectorAll('.phase-card').forEach(x=>x.classList.toggle('active',x===b));tlRender();document.getElementById('timeline-table').scrollIntoView({behavior:'smooth',block:'start'});}));}
function tlQueueMatch(r,v){if(v==='all')return true;if(v==='zero-timing')return r.zero;if(v==='strong-culture-zero')return r.zero&&r.breadth>=55;if(v==='current')return r.current>0;if(v==='historical-only')return r.historicalOnly;if(v==='thin')return r.thin;if(v==='dense')return r.dense;return true;}
function tlFiltered(){const q=document.getElementById('timeline-search').value.trim().toLowerCase(),st=document.getElementById('timeline-state').value,phase=document.getElementById('timeline-phase').value,status=document.getElementById('timeline-status').value,queue=document.getElementById('timeline-gap').value,sort=document.getElementById('timeline-sort').value;let rows=TL_ROWS.filter(r=>{if(st!=='all'&&r.college.state!==st)return false;if(q&&![r.id,r.college.name,tlFormatName(r.college.name),r.college.city,r.college.state].join(' ').toLowerCase().includes(q))return false;if(!tlQueueMatch(r,queue))return false;if(phase!=='all'){const p=r.phases.find(x=>x.key===phase);if(status==='missing'&&p.grade!=='GAP')return false;if(status==='supported'&&!TL_PUBLISHABLE.has(p.grade))return false;if(status==='lead'&&p.grade!=='D')return false;}else if(status!=='all'){if(status==='missing'&&!r.zero)return false;if(status==='supported'&&r.supported===0)return false;if(status==='lead'&&r.lead===0)return false;}return true;});if(sort==='coverage-desc')rows.sort((a,b)=>b.supported-a.supported||b.breadth-a.breadth||a.college.name.localeCompare(b.college.name));else if(sort==='coverage-asc')rows.sort((a,b)=>a.supported-b.supported||b.priority-a.priority||a.college.name.localeCompare(b.college.name));else if(sort==='culture')rows.sort((a,b)=>b.breadth-a.breadth||a.supported-b.supported||a.college.name.localeCompare(b.college.name));else if(sort==='name')rows.sort((a,b)=>a.college.name.localeCompare(b.college.name));else rows.sort((a,b)=>b.priority-a.priority||b.breadth-a.breadth||a.college.name.localeCompare(b.college.name));return rows;}
function tlPriority(r){if(r.priority>=18)return ['High timing gap','high'];if(r.priority>=12)return ['Medium gap','med'];return ['Lower gap',''];}
function tlCell(p){const sup=TL_PUBLISHABLE.has(p.grade),lead=p.grade==='D',cl=sup?'supported':lead?'lead':'gap';const status=sup?(p.status||p.basis||'supported'):lead?'lead only':'missing';return `<div class="tl-cell ${cl} grade-${tlEsc(p.grade)}" title="${tlEsc(p.summary||'')}"><span class="g">${sup||lead?tlEsc(p.grade):'—'}</span><span class="s">${tlEsc(status)}</span></div>`;}
function tlRender(){const rows=tlFiltered(),root=document.getElementById('timeline-table');document.getElementById('timeline-count').textContent=`${rows.length} of ${TL_ROWS.length} researched profiles shown`;document.querySelectorAll('.phase-card').forEach(x=>x.classList.toggle('active',x.dataset.phase===document.getElementById('timeline-phase').value&&document.getElementById('timeline-status').value==='missing'));if(!rows.length){root.innerHTML='<div class="empty-timeline">No profiles match these timeline filters.</div>';return;}const head=`<div class="timeline-row head"><div>College</div><div>Coverage</div>${TL_PHASES.map(p=>`<div>${tlEsc(p.short||p.label)}</div>`).join('')}<div>Research gap</div></div>`;root.innerHTML=head+rows.map(r=>{const [pl,pc]=tlPriority(r);return `<article class="timeline-row"><div class="tl-name"><a href="college.html?id=${r.id}">${tlEsc(tlFormatName(r.college.name))}</a><div class="tl-loc">${tlEsc(r.college.city)}, ${tlEsc(r.college.state)} · ${r.first90}/5 First-90 fields · ${r.source.classes}/3 source classes</div><div class="tl-actions"><a href="college.html?id=${r.id}">Profile</a><a href="compare.html?c=${r.id}">Compare</a><a href="culture.html">Culture</a></div></div><div class="tl-score">${r.supported}/6<small>${r.current?`${r.current} current-2026`:r.historicalOnly?'historical-only':r.lead?`${r.lead} lead-only`:r.zero?'no timing':'timing evidence'}</small></div>${r.phases.map(tlCell).join('')}<div class="tl-priority ${pc}">${r.priority}<small>${tlEsc(pl)}</small></div></article>`;}).join('');}
function tlInit(){tlSetTheme();tlPopulate();tlStats();tlPhaseSummary();['timeline-search','timeline-state','timeline-phase','timeline-status','timeline-gap','timeline-sort'].forEach(id=>{const el=document.getElementById(id);el.addEventListener(id==='timeline-search'?'input':'change',tlRender);});tlRender();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',tlInit);else tlInit();
