(()=>{
  const SHORT='shortlist', ORDER='preference_order', COMP='merit-register-compare-colleges';
  const page=(()=>{const p=(location.pathname.split('/').pop()||'index.html').toLowerCase();return p||'index.html';})();
  const productPages=['index.html','compare.html','preference.html','decision.html','choice.html'];
  const steps=[
    ['index.html','Find','⌕'],['compare.html','Compare','⇄'],['preference.html','My List','♡'],['decision.html','Decide','◇'],['choice.html','Choice','✓']
  ];
  const safeParse=(v,f)=>{try{const x=JSON.parse(v);return x??f}catch{return f}};
  const uniqueIds=v=>[...new Set((Array.isArray(v)?v:[]).map(Number).filter(Number.isFinite))];
  function storageWorks(){try{const k='__tmr_test__';localStorage.setItem(k,'1');localStorage.removeItem(k);return true}catch{return false}}
  function read(k){try{return uniqueIds(safeParse(localStorage.getItem(k)||'[]',[]))}catch{return []}}
  function write(k,v){try{localStorage.setItem(k,JSON.stringify(uniqueIds(v)));return true}catch{return false}}
  function normalizeLists(){if(!storageWorks())return;const shortlist=read(SHORT), rawOrder=read(ORDER);const sset=new Set(shortlist);const order=rawOrder.filter(id=>sset.has(id));shortlist.forEach(id=>{if(!order.includes(id))order.push(id)});if(JSON.stringify(order)!==JSON.stringify(rawOrder))write(ORDER,order);const cmp=read(COMP).slice(0,4);if(JSON.stringify(cmp)!==JSON.stringify(read(COMP)))write(COMP,cmp);}
  function listCount(){return new Set(read(SHORT)).size}
  function updateMyList(){const n=listCount();document.querySelectorAll('[data-my-list-link]').forEach(a=>{a.innerHTML='♡ My List'+(n?` <span class="nav-count" aria-label="${n} colleges in My List">${n}</span>`:'');});document.querySelectorAll('[data-ux-list-count]').forEach(x=>x.textContent=String(n));}
  function ensureToast(){let t=document.getElementById('ux-toast');if(t)return t;t=document.createElement('div');t.id='ux-toast';t.className='ux-toast';t.setAttribute('role','status');t.setAttribute('aria-live','polite');document.body.appendChild(t);return t}
  let toastTimer;
  function toast(msg,html=false){const t=ensureToast();clearTimeout(toastTimer);if(html)t.innerHTML=msg;else t.textContent=msg;t.classList.add('show');toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
  window.meritUxToast=toast;
  function storageWarning(){if(storageWorks())return;const x=document.createElement('div');x.className='ux-storage-warning';x.innerHTML='<strong>Browser saving is unavailable.</strong> My List, theme and candidate settings may disappear when you leave this page.';document.body.insertBefore(x,document.body.firstChild)}
  function skipLink(){if(document.querySelector('.skip-link'))return;const main=document.querySelector('main')||document.querySelector('section');if(!main)return;if(!main.id)main.id='main-content';const a=document.createElement('a');a.href='#'+main.id;a.className='skip-link';a.textContent='Skip to main content';document.body.insertBefore(a,document.body.firstChild)}
  function filters(){const d=document.querySelector('#directory-filter-drawer');if(!d)return;const sync=()=>{if(matchMedia('(min-width:901px)').matches)d.open=true};sync();addEventListener('resize',sync);
    const toolbar=document.querySelector('.directory-toolbar');if(!toolbar||document.querySelector('.directory-filter-tools'))return;
    const box=document.createElement('div');box.className='directory-filter-tools';box.innerHTML='<span class="directory-filter-status" id="directory-filter-status">No extra filters</span><button class="directory-filter-clear" type="button">Clear filters</button>';
    toolbar.appendChild(box);const status=box.querySelector('#directory-filter-status'),clear=box.querySelector('button');
    const fields=[...toolbar.querySelectorAll('select')].filter(x=>x.id!=='sort-select').concat([...toolbar.querySelectorAll('.chip-row .active')]);
    const count=()=>{let n=0;toolbar.querySelectorAll('select').forEach(s=>{if(s.id!=='sort-select'&&s.value)n++});const search=document.getElementById('search-input');if(search?.value.trim())n++;status.textContent=n?`${n} active filter${n===1?'':'s'}`:'No extra filters';clear.hidden=n===0};
    toolbar.addEventListener('change',()=>setTimeout(count,0));document.getElementById('search-input')?.addEventListener('input',()=>setTimeout(count,0));
    clear.addEventListener('click',()=>{toolbar.querySelectorAll('select').forEach(s=>{if(s.id!=='sort-select'){s.value='';s.dispatchEvent(new Event('change',{bubbles:true}))}});const search=document.getElementById('search-input');if(search){search.value='';search.dispatchEvent(new Event('input',{bubbles:true}))}document.querySelectorAll('#type-chips .active').forEach(b=>b.click());count();toast('Filters cleared');});count();
  }
  function decisionPresets(){document.querySelectorAll('[data-ux-preset]').forEach(b=>b.addEventListener('click',()=>{const target=document.querySelector(`[data-preset="${b.dataset.uxPreset}"]`);if(target){target.click();document.querySelector('.decision-main')?.scrollIntoView({behavior:'smooth',block:'start'});}}));}
  function workflow(){if(!productPages.includes(page)||page==='index.html'||document.querySelector('.workflow-strip'))return;const strip=document.createElement('nav');strip.className='workflow-strip';strip.setAttribute('aria-label','Decision workflow');const current=Math.max(0,steps.findIndex(s=>s[0]===page));strip.innerHTML=`<div class="wrap">${steps.map((s,i)=>`<a href="${s[0]}" class="workflow-step ${i===current?'active':i<current?'done':''}" ${i===current?'aria-current="step"':''}><span class="workflow-num">${i+1}</span>${s[1]}</a>`).join('')}</div>`;const head=document.querySelector('header.masthead');head?.insertAdjacentElement('afterend',strip)}
  function mobileNav(){if(document.querySelector('.mobile-quick-nav'))return;const nav=document.createElement('nav');nav.className='mobile-quick-nav';nav.setAttribute('aria-label','Quick navigation');const items=[['index.html','⌕','Find'],['compare.html','⇄','Compare'],['preference.html','♡','My List'],['choice.html','✓','Choice']];nav.innerHTML=items.map(([href,ico,lab])=>`<a href="${href}" class="${page===href?'active':''}" ${page===href?'aria-current="page"':''}><strong>${ico}</strong><span>${lab}${href==='preference.html'?` · <span data-ux-list-count>${listCount()}</span>`:''}</span></a>`).join('');document.body.appendChild(nav)}
  function heroChoiceLink(){if(page!=='index.html'||document.querySelector('.hero-next-step'))return;const paths=document.querySelector('.hero-paths');if(!paths)return;const p=document.createElement('p');p.className='hero-next-step';p.innerHTML='Already have a shortlist? <a href="choice.html">Check your final counselling order →</a>';paths.insertAdjacentElement('afterend',p)}
  function preferenceCta(){if(page!=='preference.html')return;const actions=document.querySelector('.pref-actions');if(actions&&!actions.querySelector('a[href="choice.html"]')){const a=document.createElement('a');a.className='btn';a.href='choice.html';a.textContent='Open Choice Filling';actions.prepend(a)}}
  function choiceProgress(){if(page!=='choice.html'||document.querySelector('.choice-progress'))return;const main=document.querySelector('.choice-main .wrap')||document.querySelector('.choice-main');if(!main)return;const x=document.createElement('div');x.className='choice-progress';x.innerHTML='<div><span>Step 1</span><strong>Confirm AIR & category</strong></div><div><span>Step 2</span><strong>Check and reorder preferences</strong></div><div><span>Step 3</span><strong>Copy/export for final verification</strong></div>';main.insertBefore(x,main.firstChild)}
  function compareHelper(){if(page!=='compare.html')return;const block=document.querySelector('.college-search-block');if(!block||document.querySelector('.ux-compare-helper'))return;const x=document.createElement('div');x.className='ux-inline-note ux-compare-helper';const n=listCount();x.innerHTML=n?`<strong>${n} college${n===1?'':'s'} in My List.</strong> Search above to compare any college, or open <a href="preference.html">My List</a> to review your saved shortlist.`:'<strong>New here?</strong> Search any two colleges above. You can save promising colleges to <a href="preference.html">My List</a> from their profiles.';block.insertAdjacentElement('afterend',x)}
  function reliabilityEvents(){window.addEventListener('error',e=>{if(e.target&&['SCRIPT','LINK'].includes(e.target.tagName)){if(document.querySelector('.ux-runtime-warning'))return;const x=document.createElement('div');x.className='ux-runtime-warning';x.innerHTML='<strong>Part of this page did not load.</strong> Reload once; if the problem persists, verify using the linked source pages rather than relying on incomplete output.';document.body.insertBefore(x,document.body.firstChild)}},true)}
  function actionFeedback(){document.addEventListener('click',e=>{const target=e.target.closest('.star-btn,#profile-pref-btn,[data-shortlist],[data-remove-shortlist]');if(target){const before=listCount();setTimeout(()=>{normalizeLists();updateMyList();const after=listCount();if(after>before)toast(`Added to My List · ${after}`);else if(after<before)toast(`Removed from My List · ${after}`);},35)}});addEventListener('storage',e=>{if([SHORT,ORDER,COMP].includes(e.key)){normalizeLists();updateMyList()}})}
  function navA11y(){document.querySelectorAll('.nav-more-btn').forEach(b=>{b.setAttribute('aria-haspopup','true');const menu=b.parentElement?.querySelector('.nav-more-menu');if(menu&&!menu.id){menu.id='nav-more-menu'}if(menu)b.setAttribute('aria-controls',menu.id)});}
  document.addEventListener('DOMContentLoaded',()=>{normalizeLists();storageWarning();skipLink();updateMyList();filters();decisionPresets();workflow();mobileNav();heroChoiceLink();preferenceCta();choiceProgress();compareHelper();navA11y();reliabilityEvents();actionFeedback();});
})();
