'use strict';
(function(){
  const BUILD='V9.0 RC';
  const FEEDBACK_KEY='merit-register-beta-feedback-v1';
  const WELCOME_KEY='merit-register-v9-beta-welcome-seen';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeGet=(k,fallback=null)=>{try{const v=localStorage.getItem(k);return v===null?fallback:v}catch(e){return fallback}};
  const safeSet=(k,v)=>{try{localStorage.setItem(k,v);return true}catch(e){return false}};
  const currentCollege=()=>{try{const q=new URLSearchParams(location.search),id=q.get('id');if(!id)return null;let c=(typeof COLLEGE_BY_ID!=='undefined'&&(COLLEGE_BY_ID[id]||COLLEGE_BY_ID[Number(id)]))||null;if(!c&&typeof ALL_COLLEGES!=='undefined')c=ALL_COLLEGES.find(x=>Number(x.id)===Number(id))||null;return c?{id:Number(id),name:c.name}:null}catch(e){return null}};
  function addBadge(){const h=document.querySelector('.masthead h1');if(!h||h.querySelector('.beta-build-badge'))return;const b=document.createElement('span');b.className='beta-build-badge';b.textContent='V9.0 RC';h.appendChild(b);}
  function addWelcome(){if(!/\/(index\.html)?$/.test(location.pathname)&&!location.pathname.endsWith('index.html'))return;if(safeGet(WELCOME_KEY))return;const hero=document.querySelector('.home-hero .wrap')||document.querySelector('main')||document.body;const box=document.createElement('div');box.className='beta-welcome';box.innerHTML='<div><strong>V9.0 RC</strong><p>The major features are frozen. This beta is for testing real counselling flows and catching wrong, stale or confusing data. Reach is never used to reorder your genuine preferences.</p></div><button type="button">Got it</button>';box.querySelector('button').onclick=()=>{safeSet(WELCOME_KEY,'1');box.remove()};hero.prepend(box);}
  function readQueue(){try{const v=JSON.parse(safeGet(FEEDBACK_KEY,'[]'));return Array.isArray(v)?v:[]}catch(e){return []}}
  function reportText(r){return [`The Merit Register — ${BUILD} issue report`,`Type: ${r.type}`,`Page: ${r.page}`,r.college?`College: ${r.college.name} (ID ${r.college.id})`:null,`Created: ${r.created}`,`Issue: ${r.note}`,r.expected?`Expected / correction: ${r.expected}`:null,r.source?`Suggested source: ${r.source}`:null].filter(Boolean).join('\n');}
  async function copy(text){try{await navigator.clipboard.writeText(text);return true}catch(e){return false}}
  function openReporter(){let ov=document.getElementById('beta-report-overlay');if(!ov){ov=document.createElement('div');ov.id='beta-report-overlay';ov.className='beta-report-overlay';ov.innerHTML=`<div class="beta-report-dialog" role="dialog" aria-modal="true" aria-labelledby="beta-report-title"><div class="beta-report-head"><div><div class="eyebrow">Beta feedback</div><h2 id="beta-report-title">Report incorrect or confusing data</h2></div><button class="beta-report-close" type="button" aria-label="Close">×</button></div><p class="beta-report-meta">Nothing is sent automatically. The report is saved in this browser so you can copy it into an issue, email or message.</p><label>Issue type<select id="beta-report-type"><option>Incorrect data</option><option>Outdated data</option><option>Missing source</option><option>Confusing wording</option><option>Broken interaction</option><option>Other</option></select></label><label>What looks wrong?<textarea id="beta-report-note" required placeholder="Describe the field, number or interaction…"></textarea></label><label>What should it say / do instead?<textarea id="beta-report-expected" placeholder="Optional correction or expected behavior"></textarea></label><label>Source that supports the correction<input id="beta-report-source" type="url" placeholder="Optional URL"/></label><div class="beta-report-actions"><button type="button" id="beta-report-save">Save report</button><button type="button" id="beta-report-copy">Copy report</button><button type="button" id="beta-report-export">Export saved reports</button></div><div class="beta-report-status" id="beta-report-status"></div></div>`;document.body.appendChild(ov);ov.querySelector('.beta-report-close').onclick=()=>ov.classList.remove('open');ov.onclick=e=>{if(e.target===ov)ov.classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape')ov.classList.remove('open')});
      const make=()=>({build:BUILD,type:document.getElementById('beta-report-type').value,page:location.href,college:currentCollege(),created:new Date().toISOString(),note:document.getElementById('beta-report-note').value.trim(),expected:document.getElementById('beta-report-expected').value.trim(),source:document.getElementById('beta-report-source').value.trim()});
      document.getElementById('beta-report-save').onclick=()=>{const r=make(),st=document.getElementById('beta-report-status');if(!r.note){st.textContent='Describe the issue first.';return}const q=readQueue();q.push(r);st.textContent=safeSet(FEEDBACK_KEY,JSON.stringify(q))?`Saved locally · ${q.length} report${q.length===1?'':'s'} in this browser.`:'Could not save in browser storage.'};
      document.getElementById('beta-report-copy').onclick=async()=>{const r=make(),st=document.getElementById('beta-report-status');if(!r.note){st.textContent='Describe the issue first.';return}st.textContent=(await copy(reportText(r)))?'Copied structured report.':'Clipboard unavailable — use Save report and export instead.'};
      document.getElementById('beta-report-export').onclick=()=>{const q=readQueue(),st=document.getElementById('beta-report-status');if(!q.length){st.textContent='No saved reports in this browser yet.';return}const blob=new Blob([JSON.stringify({build:BUILD,exported:new Date().toISOString(),reports:q},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='merit-register-v9-beta-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);st.textContent=`Exported ${q.length} saved report${q.length===1?'':'s'}.`};
    }
    ov.classList.add('open');setTimeout(()=>document.getElementById('beta-report-note')?.focus(),0);
  }
  function addReporter(){if(document.querySelector('.beta-report-fab'))return;const b=document.createElement('button');b.type='button';b.className='beta-report-fab';b.textContent='Report data issue';b.onclick=openReporter;document.body.appendChild(b);}
  function addDataNote(){if(!location.pathname.endsWith('college.html'))return;const target=document.querySelector('.profile-cutoff-note')||document.querySelector('main');if(!target||document.querySelector('.beta-data-note'))return;const d=document.createElement('div');d.className='beta-data-note';d.innerHTML='<strong>Beta data check</strong><span>See something wrong or stale? Use <em>Report data issue</em>. Absence of evidence is never treated as a positive finding.</span>';target.insertAdjacentElement('afterend',d);}
  function init(){addBadge();addWelcome();addReporter();addDataNote();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
